title: Drive//Shaft
author: Alex Schearer
email: ascherer@spottedzebra.us
description: > # this means to ignore newlines until "baseurl:"
  "Drive//Shaft is an open-world, physics-based, multiplayer car racing game."

twitter_username: ZebraSpotted
github_username:  aschearer

sass:
    style: compressed

google_analytics: UA-34116305-6
facebook_pixel: 227502131157258